- .github/workflows/ci.yml
- README.md
> chore: remove Codecov token

- .github/workflows/ci-deep.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-archive.yml
- .github/workflows/deploy-periphery.yml
- .github/workflows/deploy-protocol.yml
- .github/workflows/deploy-proxy-plugin.yml
- .github/workflows/deploy-proxy-target.yml
- .github/workflows/list-in-archive.yml
- test/fork/Fork.t.sol
> test: mainnet fork

- src/SablierV2ProxyTarget.sol
- src/interfaces/ISablierV2ProxyTarget.sol
- src/types/DataTypes.sol
- src/types/Permit2.sol
- src/types/Proxy.sol
- test/fork/plugin/onStreamCanceled.t.sol
- test/fork/target/batchCreate.t.sol
- test/integration/target/batch-create-with-deltas/batchCreateWithDeltas.t.sol
- test/integration/target/batch-create-with-durations/batchCreateWithDurations.t.sol
- test/integration/target/batch-create-with-milestones/batchCreateWithMilestones.t.sol
- test/integration/target/batch-create-with-range/batchCreateWithRange.t.sol
- test/integration/target/cancel-and-create/cancelAndCreate.t.sol
- test/utils/Defaults.sol
> feat: re-export types

- src/interfaces/ISablierV2ProxyPlugin.sol
- src/interfaces/ISablierV2ProxyTarget.sol
> docs: nitpicks

- test/fork/target/batchCancelMultiple.t.sol
> test: fix first stream id assumption

- package.json
- pnpm-lock.yaml
- test/fork/Fork.t.sol
- test/fork/target/batchCancelMultiple.t.sol
Bumps PRBProxy to v4.0.1:
https://github.com/PaulRBerg/prb-proxy/releases/tag/v4.0.1
> build: bump proxy

- CHANGELOG.md
- package.json
> docs: roll v1.0.1

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
> build: bump v2-core

- test/integration/airstream/campaign-factory/create-airstream-campaign-ll/createAirstreamCampaignLL.t.sol
- test/integration/airstream/campaign-factory/create-airstream-campaign-ll/createAirstreamCampaignLL.tree
- test/integration/airstream/campaign-factory/get-airstream-campaigns/getAirstreamCampaigns.t.sol
- test/integration/airstream/campaign-factory/get-airstream-campaigns/getAirstreamCampaigns.tree
- test/integration/airstream/campaign-ll/claim/claim.t.sol
- test/integration/airstream/campaign-ll/claim/claim.tree
- test/integration/airstream/campaign-ll/clawback/clawback.t.sol
- test/integration/airstream/campaign-ll/clawback/clawback.tree
- test/integration/airstream/campaign-ll/has-claimed/hasClaimed.t.sol
- test/integration/airstream/campaign-ll/has-claimed/hasClaimed.tree
- test/integration/archive/list/list.t.sol
- test/integration/archive/list/list.tree
- test/integration/archive/unlist/unlist.t.sol
- test/integration/archive/unlist/unlist.tree
- test/integration/plugin/on-stream-canceled/onStreamCanceled.t.sol
- test/integration/plugin/on-stream-canceled/onStreamCanceled.tree
Closes https://github.com/sablier-labs/v2-periphery/issues/167
> test: use "given" keyword in branching trees

- .github/workflows/ci.yml
Closes https://github.com/sablier-labs/v2-periphery/issues/180
> ci: cache testing contracts

- package.json
Depends on https://github.com/sablier-labs/v2-periphery/pull/191
> build: remove oz peer deps

- CHANGELOG.md
- package.json
Depends on https://github.com/sablier-labs/v2-periphery/pull/194
> docs: roll 1.1.0

- .gitmodules
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
Closes https://github.com/sablier-labs/v2-periphery/issues/197
> build: install permit2 from uniswap repo

- src/SablierV2MerkleStreamerLL.sol
- src/abstracts/SablierV2MerkleStreamer.sol
The `_setClaimed` internal function isn't really needed
> refactor: remove "_setClaimed"

- CONTRIBUTING.md
> docs: add guidelines for fork testing

- .github/workflows/stale.yml
Experimenting with https://github.com/marketplace/actions/close-stale-issues
> ci: bot for closing stale issues and PR

- foundry.toml
- script/Base.s.sol
- script/DeployDeterministicBatch.s.sol
- script/DeployDeterministicPeriphery.s.sol
- test/utils/BaseScript.t.sol
Same as here https://github.com/sablier-labs/v2-core/pull/814
> feat: add a util function to construct the create2 salt

- .github/workflows/ci-fork.yml
- .github/workflows/ci.yml
Same as here https://github.com/sablier-labs/v2-core/pull/824
> ci: run fork tests only monday, wednesday and friday

- SECURITY.md
Refer to https://github.com/sablier-labs/v2-periphery/discussions/311 for motivation.
> docs: update security assumptions

- .github/workflows/ci.yml
Same as https://github.com/sablier-labs/v2-core/pull/901
> ci: add `staging-blast` and `staging` to `ci.yml`

- foundry.toml
- script/Base.s.sol
- test/utils/BaseScript.t.sol
Same as https://github.com/sablier-labs/v2-core/pull/907.
Related discussion: https://github.com/sablier-labs/v2-core/discussions/904.
> build: replace ffi with stdJson for salt creation

- .github/workflows/ci-deep.yml
Fixes similar issue as https://github.com/sablier-labs/v2-core/issues/965 in v2-periphery.
Before changes: https://github.com/sablier-labs/v2-periphery/actions/runs/9828216614
After changes: https://github.com/sablier-labs/v2-periphery/actions/runs/9828236839
> ci: use `fromJSON` to convert string into digits

- src/types/DataTypes.sol
> refactor: remove `CancelMultiple` struct

- README.md
Once the repo is going to be archived, this is going to be useful for the `README`
Closes https://github.com/sablier-labs/v2-periphery/issues/386
> docs: mention in README that the repo is archived
